import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    globals: false,
    clearMocks: true,
    restoreMocks: true,
    fileParallelism: false,
    include: ["src/**/*.test.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary", "html"],
      reportsDirectory: "coverage",
      include: ["src/**/*.ts"],
      exclude: ["src/**/*.test.ts", "src/generated/**"],
      thresholds: {
        lines: 70,
        functions: 70,
        branches: 70,
        statements: 70,
      },
    },
    env: {
      NODE_ENV: "test",
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/chat_test",
      FRONTEND_ORIGIN: "http://localhost:3000",
      JWT_ACCESS_SECRET: "test-only-secret-with-at-least-32-bytes",
      JWT_ISSUER: "chat-api-test",
      JWT_AUDIENCE: "chat-web-test",
      LOG_LEVEL: "silent",
      STORAGE_ENDPOINT: "http://localhost:9000",
      STORAGE_REGION: "us-east-1",
      STORAGE_ACCESS_KEY_ID: "chat-local-access",
      STORAGE_SECRET_ACCESS_KEY: "chat-local-secret-key",
      STORAGE_FORCE_PATH_STYLE: "true",
      STORAGE_AVATAR_BUCKET: "chat-avatars",
      STORAGE_ATTACHMENT_BUCKET: "chat-attachments",
      STORAGE_PUBLIC_BASE_URL: "http://localhost:9000/chat-avatars",
      AVATAR_UPLOAD_URL_TTL_SECONDS: "600",
      MEDIA_CLEANUP_INTERVAL_MS: "900000",
      MEDIA_STALE_UPLOAD_AGE_MS: "3600000",
      AVATAR_CACHE_CONTROL: "public, max-age=86400",
    },
  },
});
